// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvdpixukmfmawdsglvpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2ZHBpeHVrbWZtYXdkc2dsdnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NDQ1NTUsImV4cCI6MjA3NTMyMDU1NX0.LAuQ-7s7tekljhxFsDT1AsnofSv9EzFamcBnH2BUTCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});